### ISSUE TITLE
Elasticsearch Node

### ISSUE THREAD

**Issue by occidere** [occidere/TIL#127]
# Node
ES 인스턴스를 실행하면 노드를 실행하게 된다. 연결된 노드들의 집합을 컬렉션이라 부른다. 만일 싱글 노드로 구성하였다면, 한개의 노드를 가진 클러스터가 된다.

클러스터 내 모든 노드들은 기본적으로 HTTP와 Transport 트래픽을 처리할 수 있다. Transport 계층은 노드들 간 통신에 독점적으로 사용되며, HTTP 계층은 REST 클라이언트로 사용된다.

모든 노드들은 클러스터 내 다른 노드들을 알고 있으며, 클라이언트의 요청을 적절한 노드로 포워딩 할 수 있다.

기본적으로 노드들은 다음의 유형 중 하나이다: master-eligible, data, ingest 그리고 machine learning (가능 시)

>클러스터가 증가하고 특히 대규모 시스템 학습 작업이 있는 경우 master-eligible 노드와 전용 data 노드 및 전용 machine learning 노드를 서로 분리하는 것을 고려하는것이 좋다.

<br>

#### Master-eligible node
- `node.master` 값이 `true` (default)로 설정되어 있는 노드로, 클러스터를 제어하는 Master 로 선정될 자격이  있는 노드

#### Data node
- `node.data` 값이 `true` (default)로 설정되어 있는 노드로, 데이터를 저장하며 데이터와 연관된 CRUD, 검색, aggregation 작업 등을 진행하는 노드

#### Ingest node
- `node.ingest` 값이 `true` (default)로 설정되어 있는 노드로, 인덱싱 전 데이터를 변형 및 추가하기 위한 ingest pipeline을 적용할 수 있는 노드. ingest 부하가 높은 경우 master 노드와 data 노드를 `node.ingest: false`로 설정하고 별도의 ingest 노드를 두는것이 좋음

#### Machine learning node
- `xpack.ml.enabled`와 `node.ml` 설정이 `ture`로 되어있는 노드로, Elasticsearch 의 배포판에 기본으로 적용되어 있는 노드. 머신러닝 기능을 사용하려면 클러스터에 하나 이상의 머신러닝 노드가 있어야 하며, 자세한 내용은 [Elastic Stack의 머신러닝 항목](https://www.elastic.co/guide/en/machine-learning/current/index.html)을 참고
    >만일 OSS-only 배포판을 사용한다면 `node.ml` 설정을 사용하면 안됨. 그렇지 않으면 노드 실행이 불가

<br>

>Coordinating node
>검색, bulk-indexing 과 같은 요청은 서로 다른 데이터 노드에 저장된 데이터를 포함할 수 있다. 예를 들어, 검색 요청은 클라이언트 Coordinating node라 불리는 요청을 수신하는 노드에 의해 조정되는 두 단계로 실행된다.
>
>Scatter phase 에선 coordinating 노드는 데이터를 보관중인 data 노드로 요청을 전달한다. 각 data 노드는 요청을 내부적으로 실행하고 결과를 coordinating 노드로 반환한다.
>Gather phase 에선 coordinating 노드는 각 데이터 노드에서 보낸 결과를 하나의 global resultset으로 reduce한다.
>
>모든 노드는 암묵적으로 coordinating 노드다. 즉, `node.master`, `node.data` 및 `node.ingest` 값이 모두 false로 설정된 노드는 전용 coordinating 노드 역할만 하며, 이를 비활성화할 수 없다. 결과적으로, 그러한 전용 coordinating 노드는 gather phase를 처리하기 위해 충분한 메모리와 CPU가 필요하다.

<br>

### Master-eligible node
Master 노드는 인덱스 생성, 삭제, 클러스터에 포함된 node 추적, shards를 어느 노드에 할당할지 결정하는 등의 작업을 클러스터 전반에 걸쳐 수행하는 노드이다. 클러스터 상태를 위해 안정적인 마스터 노드를 갖는 것이 중요하다.

voting-only 노드가 아닌 모든 master-eligible 노드는 마스터 선출 프로세스에 의해 마스터 노드로 선택될 수 있다.

>Master 노드는 data 노드와 마찬가지로 노드 재시작이 이뤄지는 사이에 클러스터의 상태가 저장되는 `data/` 디렉토리 접근 권한이 있어야 한다.

<br>

### Dedicated master-eligible node
선출된 마스터 노드가 그 책임을 이행하는 데 필요한 자원을 보유하는 것은 클러스터의 안정성에 있어 중요하다.
마스터 노드가 다른 작업으로 인해 과부하가 걸린다면 클러스터가 제대로 동작하지 않을 수 있다.
특히 데이터를 인덱싱하고 검색하는 것은 높은 리소스를 필요로 하므로, 대규모 또는 높은 처리량을 필요로 하는 클러스터에선 인덱싱 및 검색과 같은 작업에 master-eligible 노드를 사용하지 않는 것이 좋다.
master-eligible 노드들 중 3개를 전용 master 노드로 두어 클러스터를 관리하는데 집중하는 `master` 역할만 수행하게 할 수 있다.
마스터 노드는 또한 coordinating 노드의 역할도 할 수 있어서 클라이언트로 부터 데이터 노드로 가는 검색 및 색인 요청을 라우팅 할 수도 있으나, 마스터 전용 노드인 경우 그렇게 하지 않는 것이 좋다.

기본 배포판에서 전용 master 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: true (default: true)
node.voting_only: false (default: false)
node.data: false (default: true)
node.ingest: false (default: true)
node.ml: false (default: true)
xpack.ml.enabled: true (default: true)
cluster.remote.connect: false (default: true)
```

OSS-only 배포판에서 master 전용 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: true (default: true)
node.data: false (default: true)
node.ingest: false (default: true)
cluster.remote.connect: false (default: true)
```

<br>

### Voting-only master-eligible node
Voting-only master-eligible node 는 master 투표엔 참여하나, master 로 선출되지는 않는 노드이다. 
Voting-only node 를 설명 시 master 로 선정될 수 없음에도 불구하고 master-eligible 이란 용어를 사용해서 혼란스러울 수도 있다. 이 용어는 과거의 불운한 결과로 인해 초래된 것이다. Master-eligible 노드는 투표에 참여하고 클러스터 상태가 퍼블리싱 되는 동안 특정 작업을 수행하는 노드이고, Voting-only 노드는 결코 Master 노드로 선출될 수 없더라도 동일한 책임을 갖는다.

Master-eligible 노드를 voting-only 노드로 설정하는 방법은 아래와 같다.
```yml
node.voting_only: true (default: false)
```

>`voting_only` 역할은 Elasticsearch 의 기본 배포판에서만 유효하며, OSS-only 배포판은 지원하지 않는다. 만일 OSS-only 배포판을 사용중인데 `node.voting_only` 옵션을 설정했다면 노드 실행이 되지 않는다. 또한 master-eligible 노드만 voting-only 노드로 설정할 수 있음을 유의한다.

High availability (HA) 클러스터는 최소 3개의 master-eligible 노드를 필요로 하며, 그 중 적어도 2개는 voting-only 노드가 아니여야 한다. 이렇게 구성된 클러스터는 master-eligible 노드 중 하나가 죽어도 master 노드 선출을 진행할 수 있다.

Voting-only 노드가 Master 선출 투표만 하기 때문에 Master 노드에 비해 heap과 cpu가 낮아도 된다. 하지만 voting-only 노드를 포함한 모든 master-eligible 노드는 클러스터 상태를 갱신하는데 중요한 역할을 하기 때문에, 모두 저장이 빠른 스토리지와 클러스터의 나머지들과 연결하는데 지연시간이 짧은 네트워크가 필요하다.

Voting-only master-eligible 노드는 클러스터에서 다른 역할을 같이 수행할 수도 있다. Data 노드의 역할과 voting-only-master-eligible 노드의 역할을 동시에 수행하는것이 그 예이다. 반면 **전용** voting-only master-eligible 노드는 클러스터에서 voting-only master-eligible 역할을 제외한 다른 역할은 수행하지 않는 노드를 지칭한다.

전용 voting-only master-eligible 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: true (default: true)
node.voting_only: true (default: false)
node.data: false (default: true)
node.ingest: false (default: true)
node.ml: false (default: true)
xpack.ml.enabled: true (default: true)
cluster.remote.connect: false (default: true)
```

<br>

### Data Node
Data 노드는 인덱싱 된 document의 shards 를 보관한다. 또한 CRUD, search, aggregation 과 같은 데이터와 연관된 작업을 수행한다. 이 작업들은 I/O, Memory, CPU 부하가 높다. 따라서 이를 잘 모니터링 하여 과부하 발생 시 Data 노드를 추가하는 것이 중요하다.

전용 data 노드를 두는 것의 이점은 바로 Master와 Data 의 역할을 분리할 수 있다는 것이다.

기본 배포판에서 전용 data 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.voting_only: false (default: false)
node.data: true (default: true)
node.ingest: false (default: true)
node.ml: false (default: true)
cluster.remote.connect: false (default: true)
```

OSS-only 배포판에서 전용 data 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.data: true (default: true)
node.ingest: false (default: true)
cluster.remote.connect: false (default: true)
```

<br>

### Ingest Node
Ingest 노드는 하나 이상의 ingest processor 들로 구성되어 전처리 pipeline 을 수행할 수 있다. Ingest processor에 의해 수행되는 작업의 종류에 따라서 특정 작업만 수행하는 전용 ingest 노드를 둘 수도 있다.

기본 배포판에서 전용 ingest 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.voting_only: false (default: false)
node.data: false (default: true)
node.ingest: true (default: true)
node.ml: false (default: true)
cluster.remote.connect: false (default: true)
``` 

OSS-only 배포판에서 전용 ingest 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.data: false (default: true)
node.ingest: true (default: true)
cluster.remote.connect: false (default: true)
```

<br>

### Coordinating only node
Master의 역할, 데이터 보관의 역할, 문서 전처리 역할 등을 빼고 나면, 요청을 라우팅하고 검색의 reduce phase 를 처리하고, 대량 색인 요청을 분배하는 등의 역할을 담당하는 coordinating 노드가 남는다. 기본적으로 coordinating only node 는 스마트한 로드밸런서 역할을 수행한다.

전용 coordinating 노드를 두면 master-eligible 노드와 data 노드가 coordinating 을 하지 않아도 되는 이점이 있다. Coordinating 노드는 다른 모든 노드들과 마찬가지로 클러스터 상태를 분석하여 요청을 적절한 곳으로 라우팅한다.

>한 클러스터 내 너무 많은 전용 coordinating 노드를 두면 마스터 노드가 모든 노드들에 대해 클러스터 상태 갱신을 ack 받기까지 기다려야 하기에 오히려 클러스터의 부담이 증가할 수 있다. Data 노드도 동일한 역할을 할 수 있기에 전용 coordinating 노드를 두는 이점만 과대평가 해선 안된다.

기본 배포판에서 전용 Coordinating 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.voting_only: false (default: false)
node.data: false (default: true)
node.ingest: false (default: true)
node.ml: false (default: true)
cluster.remote.connect: false (default: true)
```

OSS-only 배포판에서 전용 ingest 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.data: false (default: true)
node.ingest: false (default: true)
cluster.remote.connect: false (default: true)
```

<br>

### Machine learning node (**X-Pack**)
머신 러닝 기능은 잡을 수행하고 머신러닝 API 요청을 처리하는 machine learning 노드를 제공한다. 만약 `xpack.ml.enabled` 값이 `true`이고 `node.ml` 값이 `false` 이면 해당 노드는 API 요청은 처리할 수 있으나, 잡 자체를 돌리진 못한다.

만약 머신러닝 기능을 클러스터에서 사용하고 싶다면 master-eligible 노드의 `xpack.ml.enabled` 값을 `true`로 설정하여 머신러닝 기능을 활성화해야 한다.

더 많은 내용은 [머신러닝 설정](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-settings.html) 을 참고한다.

기본 배포판에서 전용 machine learning 노드를 설정하는 방법은 아래와 같다.
```yml
node.master: false (default: true)
node.voting_only: false (default: false)
node.data: false (default: true)
node.ingest: false (default: true)
node.ml: true (default: true)
xpack.ml.enabled: true (default: true)
cluster.remote.connect: false (default: true)
```

### 노드의 역할 변경
각 data 노드는 다음과 같은 데이터를 디스크에 유지한다.
- 해당 노드에 할당된 모든 샤드들의 데이터
- 해당 노드에 할당된 모든 샤드들에 해당하는 인덱스의 메타데이터
- 세팅, 인덱스 템플릿과 같은 클러스터 전반에 걸친 메타데이터

유사하게 각 master-eligible 노드는 다음과 같은 데이터를 디스크에 보관한다.
- 클러스터 내 모든 인덱스들의 메타데이터
- 세팅, 인덱스 템플릿과 같은 클러스터 전반에 걸친 메타데이터

각 노드는 시작 시 data path의 콘텐츠를 점검한다. 만약 예기치 못한 데이터가 감지된 경우 실행되지 않는다. 이는 read cluster health 를 유도할 수 있는 의도치 않은 [dangling indices](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway-dangling-indices.html) 현상을 막기 위한 조치이다. 좀더 상세히 말하면, `node.data: false` 로 세팅된 노드는 부팅 과정 중 shard 데이터를 디스크에서 발견하면 부팅에 실패하며, `node.master: false` 와 `node.data: false` 로 세팅된 노드는 부팅 시 디스크에서 인덱스 메타데이터를 발견하면 부팅에 실패한다.

`elasticsearch.yml` 파일을 조정하고 재시작 하는것으로 노드의 역할을 변경할 수 있다. 이러한 작업은 repurposing node 로 불린다. 위에서 설명한 예기치 않은 데이터에 대한 검사를 만족시키려면 `node.data` 또는 `node.master` 역할을 false로 설정할 때 노드 repurposing을 준비하기 위한 몇 가지 추가 단계를 수행해야 한다.
- `node.data` 값을 `false`로 해서 data 노드의 역할을 바꾸고 싶으면 먼저 [allocation filter])(https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-filtering.html) 를 사용하여 안전하게 모든 shard 데이터를 클러스터 내 다른 노드로 마이그레이션 해야 한다.
- `node.master: false` 와 `node.data: false` 로 설정된 노드의 역할을 바꾸려면 empty data path 를 가진 새로운 노드로 실행하는 것이 제일 간단하다. [allocation filter])(https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-filtering.html) 로 shard 데이터를 클러스터 내 다른곳으로 우선 옮기고 작업하는 것이 제일 안전하다.

만일 위 방법들이 불가능하다면, `[elasticsearch-node repurpose](https://www.elastic.co/guide/en/elasticsearch/reference/current/node-tool.html#node-tool-repurpose)` 툴을 사용해 노드 실행을 막는 초과된 데이터들을 삭제할 수도 있다.

<br>

### `path.data`
모든 data 노드와 master-eligible 노드는 shard 와 인덱스, 클러스터 메타데이터가 저장되는 data 경로에 대한 접근 권한이 필요하다. `path.data` 는 기본적으로 `$ES_HOME/data` 로 설정되어 있으나, `elasticsearch.yml` 설정 파일에서 절대경로 또는 아래와 같이 `$ES_HOME` 을 이용해 상대경로로 설정할 수 있다.
```yml
path.data: /var/elasticsearch
```

다른 모든 노드 세팅과 동일하게 command line 으로도 명시할 수 있다.
```bash
./bin/elasticsearch -Epath.data=/var/elasticsearch/data
```

>`.zip` 또는 `.tar.gz` 배포판을 사용하는 경우 `path.data` 세팅은 Elasticsearch 홈 디렉토리 밖으로 설정하여 홈 디렉토리가 삭제될 때 데이터도 같이 지워지는 참사를 막아야 한다. RPM 이나 Debian 배포판은 이미 이 설정이 적용되어 있다.

### `node.max_local_storage_nodes`
`[data path](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-path)`는 다수의 노드들이 공유할 수 있으며, 심지어 다른 클러스터에 속한 노드도 이를 공유할 수 있다. 그러나 하나의 data path는 하나의 노드만 사용하는 것이 권장된다. 이 설정은 7.X 에서 deprecated 되었으며, 8.0에서 제거될 예정이다.

기본적으로 Elasticsearch는 하나 이상의 노드가 동일한 data path를 물고 실행되는 것을 막는다. 이를 허용하려면 `node.max_local_storage_nodes` 세팅을 1 보다 큰 양의 정수 값으로 설정하면 된다.

>절대로 master, data 노드와 같은 서로 다른 타입의 노드들을 동일한 data path 를 바라보게 해선 안된다. 이는 예상치 못한 데이터 손실을 야기할 수 있다.

## 기타 노드 세팅
더 많은 노드 설정 관련 내용은 [Modules](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules.html) 를 참고한다. 이 중에서도 특히 `[cluster.name](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.name.html)`, `[node.name](https://www.elastic.co/guide/en/elasticsearch/reference/current/node.name.html)`, `[network settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html)` 등이 주목할만 하다.

<br>

## 원문
- https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

<br>

## 참고
- [Elasticsearch 노드 정리](https://github.com/occidere/TIL/issues/43)

<br>
